--3. Transfers by Company and Branch Plant
SELECT C.COMPANYNAME, BR.BPNAME,SUM(EXTCOST) as total_cost, SUM(QUANTITY) as total_quantity
FROM INVENTORY_FACT F JOIN BRANCH_PLANT_DIM BR ON F.BRANCHPLANTKEY = BR.BRANCHPLANTKEY
                      JOIN COMPANY_DIM C ON C.COMPANYKEY = BR.COMPANYKEY
WHERE TRANSTYPEKEY = 2
GROUP BY ROLLUP (C.COMPANYNAME, BR.BPNAME)
ORDER BY C.COMPANYNAME, BR.BPNAME;