--6. Rewritten Query 1 without the CUBE or GROUPING SETS operators
SELECT D.CALMONTH, C.ADDRCATCODE1,SUM(EXTCOST) AS TOTAL_COST, SUM(QUANTITY)  AS TOTAL_QUANTITY
FROM INVENTORY_FACT F JOIN DATE_DIM D ON F.DATEKEY = D.DATEKEY
                      JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5 AND D.CALYEAR = 2011
GROUP BY D.CALMONTH, C.ADDRCATCODE1
UNION
SELECT D.CALMONTH, NULL,SUM(EXTCOST), SUM(QUANTITY)  
FROM INVENTORY_FACT F JOIN DATE_DIM D ON F.DATEKEY = D.DATEKEY
                      JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5 AND D.CALYEAR = 2011
GROUP BY D.CALMONTH
UNION
SELECT NULL, C.ADDRCATCODE1,SUM(EXTCOST), SUM(QUANTITY)  
FROM INVENTORY_FACT F JOIN DATE_DIM D ON F.DATEKEY = D.DATEKEY
                      JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5 AND D.CALYEAR = 2011
GROUP BY C.ADDRCATCODE1
UNION
SELECT NULL, NULL,SUM(EXTCOST), SUM(QUANTITY)  
FROM INVENTORY_FACT F JOIN DATE_DIM D ON F.DATEKEY = D.DATEKEY
                      JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5 AND D.CALYEAR = 2011
ORDER BY 1,2;