--1. Sales Order Shipments by Month and Category Code1
SELECT D.CALMONTH, C.ADDRCATCODE1,SUM(EXTCOST) AS TOTAL_COST, SUM(QUANTITY)  AS TOTAL_QUANTITY
FROM INVENTORY_FACT F JOIN DATE_DIM D ON F.DATEKEY = D.DATEKEY
                      JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5 AND D.CALYEAR = 2011
GROUP BY CUBE (D.CALMONTH, C.ADDRCATCODE1)
ORDER BY D.CALMONTH, C.ADDRCATCODE1;


