--4. Inventory Transactions by Transaction Description, Company, and Branch Plant
SELECT T.TRANSDESCRIPTION, C.COMPANYNAME, BR.BPNAME, SUM(F.EXTCOST) as TOTAL_COST, COUNT(F.INVENTORYKEY) as TOTAL_TRANSACTIONS
FROM INVENTORY_FACT F JOIN TRANS_TYPE_DIM T ON F.TRANSTYPEKEY = T.TRANSTYPEKEY
                      JOIN BRANCH_PLANT_DIM BR ON F.BRANCHPLANTKEY = BR.BRANCHPLANTKEY
                      JOIN COMPANY_DIM C ON C.COMPANYKEY = BR.COMPANYKEY
GROUP BY GROUPING SETS ((T.TRANSDESCRIPTION, C.COMPANYNAME, BR.BPNAME),
                         (T.TRANSDESCRIPTION, C.COMPANYNAME),
                         (T.TRANSDESCRIPTION),
                         ())
ORDER BY T.TRANSDESCRIPTION, C.COMPANYNAME, BR.BPNAME;